import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of Service for Job Search Query Builder.",
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-extrabold mb-6">Terms of Service</h1>
      <p className="text-sm text-gray-500 mb-8">Last updated: March 1, 2026</p>
      <div className="prose max-w-none">
        <h2>1. Acceptance of Terms</h2>
        <p>By accessing and using Job Search Query Builder ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>

        <h2>2. Description of Service</h2>
        <p>Job Search Query Builder is a free, browser-based tool that generates Boolean search queries for job boards. The Service creates Google search URLs based on your input and does not directly interact with job board APIs or databases.</p>

        <h2>3. Use of Service</h2>
        <p>You agree to use the Service only for lawful purposes and in accordance with these Terms. You agree not to:</p>
        <ul>
          <li>Use the Service for any illegal or unauthorized purpose</li>
          <li>Attempt to interfere with or disrupt the Service</li>
          <li>Use automated tools to scrape or overload the Service</li>
          <li>Misrepresent yourself or your affiliation</li>
        </ul>

        <h2>4. Intellectual Property</h2>
        <p>The Service, including its design, code, and content, is open source under the MIT License. The search queries generated by the tool are yours to use freely.</p>

        <h2>5. Disclaimer of Warranties</h2>
        <p>The Service is provided "as is" without warranties of any kind, express or implied. We do not guarantee that:</p>
        <ul>
          <li>The Service will be available at all times</li>
          <li>Search results will be accurate, complete, or current</li>
          <li>The Service will meet your specific requirements</li>
          <li>Job listings found through the Service are legitimate or currently available</li>
        </ul>

        <h2>6. Limitation of Liability</h2>
        <p>In no event shall Job Search Query Builder be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service.</p>

        <h2>7. Third-Party Services</h2>
        <p>The Service generates links to third-party websites (Google, LinkedIn, Indeed, Glassdoor, etc.). We are not affiliated with and do not control these third-party services. Your use of these services is governed by their respective terms.</p>

        <h2>8. Modifications</h2>
        <p>We reserve the right to modify or discontinue the Service at any time without notice. We may also update these Terms from time to time. Continued use after changes constitutes acceptance of the modified Terms.</p>

        <h2>9. Contact</h2>
        <p>For questions about these Terms, contact us at <a href="mailto:hello@gaganthakur.com">hello@gaganthakur.com</a>.</p>
      </div>
    </div>
  );
}
